# Generated by Django 5.0.4 on 2024-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
