# Generated by Django 5.0.4 on 2024-04-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0007_emails_delete_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
